export const COUNTRY_NAMES: Record<string, string> = {
  NG: 'Nigeria',
  GH: 'Ghana',
  KE: 'Kenya',
  UG: 'Uganda',
  TZ: 'Tanzania',
  ZA: 'South Africa',
  EG: 'Egypt',
  CM: 'Cameroon',
  BJ: 'Benin',
  CI: 'Côte d\'Ivoire',
  SN: 'Senegal',
  ML: 'Mali',
  BF: 'Burkina Faso',
  NE: 'Niger',
  TG: 'Togo',
  LR: 'Liberia',
  SL: 'Sierra Leone',
  GM: 'Gambia',
  GN: 'Guinea',
  MR: 'Mauritania',
  US: 'United States',
  CA: 'Canada',
  BR: 'Brazil',
  MX: 'Mexico',
  GB: 'United Kingdom',
  FR: 'France',
  DE: 'Germany',
  IN: 'India',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  SG: 'Singapore',
  TH: 'Thailand',
  PH: 'Philippines',
  ID: 'Indonesia',
  VN: 'Vietnam',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  AU: 'Australia',
};

export function getCountryName(countryId: string): string {
  return COUNTRY_NAMES[countryId.toUpperCase()] || countryId;
}
